### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by yathomasi** [spinach/FantasyPremierLeague-Api.py#13]
Sometimes following error occurs 
```
classic league mode
Errors occurred in getting entries/managers in the league.
'standings'
Traceback (most recent call last):
  File "playersPickedInLeague.py", line 112, in <module>
    entries = getUserEntryIds(leagueIdSelected, pageCount, leagueStandingUrl)
  File "playersPickedInLeague.py", line 35, in getUserEntryIds
    managers = jsonResponse["standings"]["results"]
KeyError: 'standings'
```
Its because of authorization error in new django api
i tried this link:https://medium.com/@bram.vanherle1/fantasy-premier-league-api-authentication-guide-2f7aeb2382e4
but it didn't worked for me 
For now you need open those link from your browser including the next page thats empty

**Comment by yathomasi** [comment]
@spinach  this issue is solved by [pull request 12](https://github.com/spinach/FantasyPremierLeague.py/pull/12) for python2 version and [pull request 14](https://github.com/spinach/FantasyPremierLeague.py/pull/14) for python3 version.
